name: Deploy
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: gzip -r docs
      - run: for file in $(find docs -type f); do mv "${file}" "${file%.gz}"; done
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --cache-control max-age=86400 --content-encoding gzip --delete --follow-symlinks
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: docs
