name: Test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn
      - run: yarn build
      - run: yarn start & yarn wait-on http://127.0.0.1:8080
      - run: yarn test
      - uses: codecov/codecov-action@v1
      - uses: actions/upload-artifact@v2
        with:
          path: cypress/screenshots
      - uses: actions/upload-artifact@v2
        with:
          path: cypress/videos
